package ec.edu.ups.app.g1.prueba.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-01-20T19:54:05.009-05:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "TitulosSOAPService", 
                  wsdlLocation = "file:/C:/Users/usuario/AppData/Local/Temp/tempdir1317434665098578211.tmp/TitulosSOAP_1.wsdl",
                  targetNamespace = "http://services.prueba.g1.app.ups.edu.ec/") 
public class TitulosSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.prueba.g1.app.ups.edu.ec/", "TitulosSOAPService");
    public final static QName TitulosSOAPPort = new QName("http://services.prueba.g1.app.ups.edu.ec/", "TitulosSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/usuario/AppData/Local/Temp/tempdir1317434665098578211.tmp/TitulosSOAP_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TitulosSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/usuario/AppData/Local/Temp/tempdir1317434665098578211.tmp/TitulosSOAP_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TitulosSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TitulosSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TitulosSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TitulosSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TitulosSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TitulosSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TitulosSOAP
     */
    @WebEndpoint(name = "TitulosSOAPPort")
    public TitulosSOAP getTitulosSOAPPort() {
        return super.getPort(TitulosSOAPPort, TitulosSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TitulosSOAP
     */
    @WebEndpoint(name = "TitulosSOAPPort")
    public TitulosSOAP getTitulosSOAPPort(WebServiceFeature... features) {
        return super.getPort(TitulosSOAPPort, TitulosSOAP.class, features);
    }

}
